#信用违约模型

#莫顿期权模型

V0 <- 100   #初始自然价值
nu <- 0.1   #漂移项
sigma <- 0.2   #波动率参数

dt <- 1/252   #delta t的长度
Time <- 1   #时间周期的终点
M <- Time/dt   #时间周期的个数

n <- 10000   #生成轨线的个数

#为了产生过程V的对数增量，需要从正态分布中使用指定的均值和标准差生成n*M个随机数
set.seed(117)
val <- rnorm(n*M, mean = (nu-sigma^2/2)*dt, sd = sigma*dt^0.5)
dlnV <- matrix(val, M, n)

#为了及时得到公司价值的变化，需要汇总增量的对数
V <- V0*exp(apply(dlnV, 2, cumsum))

#画出前50条轨线
matplot(x = seq(0+dt, Time, dt), y = V[, 1:50], type = 's', lty = 1, xlab = 'Time', ylab = 'Firm value trajectories', main = 'Trajectories of firm values in the Merton model')

r <- 0.05   #无风险利率
K <- 80   #债务面值
D <- exp(-r*Time)*mean((pmin(V[M, ], K)))    #风险债务值
D

#Black-Scholes定价公式计算信用价差

library(fOptions)
V0 - GBSOption(TypeFlag = "c", S = V0, X = K, Time = Time, r = r, b = r, sigma = sigma)@price

Time <- seq(0.1, 10, 0.1)
D <- V0- GBSOption(TypeFlag = "c", S = V0, X = K, Time = Time, r = r, b = r, sigma = sigma)@price
creditspreads <- 1/Time*log(K/D)-r
matplot(x = Time, y = creditspreads, type = 'l', xlab = 'Maturity', ylab = 'Credit spreads', main = 'Term structure of credit spreads in the Mertion model')   #信用价差曲线


#强度模型

library(sde)

Time <- 1   #时间周期终点
dt <- 1/252   #时间周期长度
M <- Time/dt   #时间周期个数

#创建CIR过程，声明初始值X0,漂移率参数theta1和theta2（theta1/theta2是长期值，theta2是调整的速度），以及波动率参数Theta3
lambda <- sde.sim(X0 = 0.1, delta = dt, T = Time, N = M, theta = c(0.05, 0.5, 0.2), model = "CIR")

n <- 5
set.seed(117)
val <- rpois(n*(M+1), lambda)
dN <- matrix(val, M+1, n)
N <- apply(dN, 2, cumsum)

matplot(x = seq(0, Time, dt), y = N[, 1:5], type = "s", xlab = "Time", ylab = "'Numver of defaults’ process trajectories", main = "Trajectories of Cox processes")

#相关违约——投资组合方法
library(copula)
norm.cop <- normalCopula(0.7)   #声明一个相关系数为0.7的高斯copula类
#生成两个随机变量的500个实现，这两个随机变量服从高斯copula相依性结构的均匀分布
set.seed(117)
u1 <- rCopula(500, norm.cop)
t.cop <- tCopula(0.7, df = 4)   #为了比较，定义一个相关系数为0.7自由度为4的tcopula类
set.seed(117)
u2 <- rCopula(500, t.cop)   #生成服从t-copula相依性的成对随机变量的500个实现

par(mfcol = c(1, 2))
plot(u1, main = "Scatter graphs of random variable pairs generated by Gaussian copula")
plot(u2, main = 'Scatter graphs of random variable pairs generated by t-copula')
par(mfcol = c(1, 1))

fit.ml <- fitCopula(norm.cop, u1, method = 'ml')
fit.ml


#迁移矩阵
library(CreditMetrics)
lgd <- 0.5
rc <- c("A", "B", "D")
M <- matrix(c(85, 13, 2, 5, 80, 15, 0, 0, 100)/100, 3, 3, dimnames = list(rc, rc), byrow = TRUE)
cm.cs(M, lgd)   #从迁移矩阵计算信用价差
