agricul <- read.csv(file = "eg11.2.csv")
attach(agricul)
plot(x, y)
lm.a <- lm(y ~ x)
summary(lm.a)
plot(x, resid(lm.a))    #残差图
re <- resid(lm.a)
abre <- abs(re)
summary(lm(abre ~ I(sqrt(x))))
summary(lm(abre ~ -1 + I(sqrt(x))))     #去掉不明显的截距项
ys <- y/(0.2576*sqrt(x))
xs <- x/(0.2576*sqrt(x))
plot(xs, ys)
lm.as <- lm(ys ~ xs)
plot(xs, resid(lm.as))
lny <- log(y)
lnx <- log(x)
plot(lny, lnx)
lm.lna <- lm(lny ~ lnx)
summary(lm.lna)
plot(lnx, resid(lm.lna))