x <- seq(1, 5, by = 0.01)
y.upper <- sqrt(3*(x^2-1))
y.lower <- -sqrt(3*(x^2-1))
y.max <- max(y.upper)
y.min <- min(y.lower)
plot(c(-5, 5), c(y.min, y.max), type = "n", xlab = "x", ylab = "y")
lines(x, y.upper); lines(x, y.lower); lines(-x, y.upper); lines(-x, y.lower)
lines(x = seq(-5, 5, by = 0.01), y = sqrt(3)*seq(-5, 5, by = 0.01)); lines(x = seq(-5, 5, by = 0.01), y = -sqrt(3)*seq(-5, 5, by = 0.01))
points(2, 0); points(-2, 0)
text(2, 0, "focus = c(2, 0)", pos = 4)
title("x^2 - 3*y^2 = 1")