attach(mtcars)
plot(wt, mpg, main = "Basic Scatter plot of MPG vs. Weight", xlab = "Car Weight (lbs/1000)",ylab = "Miles Per Gallon", pch = 19)
abline(lm(mpg ~ wt), col = "red", lwd = 2, lty = 1)
lines(lowess(wt, mpg), col = "blue", lwd = 2, lty = 2)
library(car)
scatterplot(mpg ~ wt | cyl, data = mtcars, lwd = 2, main = "Scatter Plot of MPG vs. Weight by # Cylinders", xlab = "Weight of Car (lbs/1000", ylab = "Miles Per Gallon", legend.plot=TRUE, id.method="identify", labels = row.names(mtcars), boxplots="xy")
pairs(~ mpg + disp + drat + wt, data = mtcars, main = "Basic Scatter Plot Matrix")
library(car)
scatterplotMatrix(~ mpg + disp + drat + wt, data = mtcars, spread = FALSE, lty.smooth = 2, main = "Scatter Plot Matrix via car Package")
scatterplotMatrix(~ mpg + disp + drat + wt | cyl, data = mtcars, spread = FALSE, diagonal = "histogram", main = "Scatterplot Plot Matix via car Package")
library(gclus)
mydata <- mtcars[c(1, 3, 5, 6)]   #选择所需变量
mydata.corr <- abs(cor(mydata))   #计算相关系数绝对值
mycolors <- dmat.color(mydata.corr)   #获得绘图的颜色，给定一个对称矩阵将返回一个颜色矩阵
myorder <- order.single(mydata.corr)   #重排对象，使相似的对象更靠近
cpairs(mydata, myorder, panel.colors = mycolors, gap=.5, main = "Variables Ordered and Colored by Correlation")
set.seed(1234)
n <- 10000
c1 <- matrix(rnorm(n, mean=0, sd=.5), ncol=2)
c2 <- matrix(rnorm(n, mean=3, sd=2), ncol=2)
mydata2 <- rbind(c1, c2)
mydata2 <- as.data.frame(mydata2)
names(mydata2) <- c("x", "y")
with(mydata2, plot(x, y, pch=19,main="Sctter Plot with 10000 Observations"))
with(mydata2, smoothScatter(x, y, main="Scatterplot Colored by Smoothed Densities"))
library(IDPmisc)
with(mydata2, iplot(x, y, main="Image Scatter Plot with Color Indicating Density"))
library(scatterplot3d)
attach(mtcars)
scatterplot3d(wt, disp, mpg, main = "Basic 3D Scatter Plot")
s3d <- scatterplot3d(wt, disp, mpg, pch = 16, highlight.3d = TRUE, type = "h", main = "3D Scatter Plot with Vertical Lines")
fit <- lm(mpg ~ wt + disp)
s3d$plane3d(fit)
library(rgl)
attach(mtcars)
plot3d(wt, disp, mpg, col = "red", size = 5)
library(Rcmdr)
attach(mtcars)
scatter3d(wt, disp, mpg)
attach(mtcars)
r <- sqrt(disp/pi)
symbols(wt, mpg, circles = r, inches = 0.30, fg = "white", bg = "lightblue", main = "Bubble Plot with point size proportional to displacement", ylab = "Miles Per Gallon", xlab = "Weight of Car (lbs/1000)", cex=0.6)
text(wt, mpg, rownames(mtcars), cex=0.6)
