options(digits = 2)
cor(mtcars)
library(corrgram)
corrgram(mtcars, order = TRUE, lower.panel = panel.shade, upper.panel = panel.pie, text.panel = panel.txt, main = "Correlogram of mtcars intercorrelations")
corrgram(mtcars, order = TRUE, lower.panel = panel.ellipse, upper.panel = panel.pts, text.panel = panel.txt, diag.panel = panel.minmax, main = "Correlogram of mtcars data using scatter plots and ellipses")
corrgram(mtcars, lower.panel = panel.shade, upper.panel = NULL, text.panel = panel.txt, main = "Car Mileage Data (unsorted)")